export const food = [
    {
        name: 'Athletic greens',
        protein: 0,
        carbs: 13,
        fat: 0,
    },
    {
        name: '1/2 Cup of Oatmeal',
        protein: 5,
        carbs: 27,
        fat: 2,
    },
    {
        name: 'Vegan Protein Powder',
        protein: 21,
        carbs: 6,
        fat: 1.5,
    },
    {
        name: 'Banana',
        protein: 0,
        carbs: 28,
        fat: 0,
    },
    {
        name: 'Small Guac Cup',
        protein: 0,
        carbs: 6,
        fat: 8,
    },
    {
        name: 'Publix Italian Sub',
        protein: 58,
        carbs: 101,
        fat: 50,
    },
    {
        name: 'Breakfast Protein Oatmeal',
        protein: 21,
        carbs: 44,
        fat: 3.5,
        info: '1 scoop of vegan protein, half a cup of blueberries, half a cup of dry oatmeal',
    },
    {
        name: 'Yerba Mate',
        protein: 0,
        carbs: 25,
        fat: 0,
    },
    {
        name: 'Home Smoothie',
        protein: 51,
        carbs: 41,
        fat: 3.5,
        info: '1 scoop of vegan protein, 1 scoop of isopure protein, half a cup of frozen fruit (8 carbs), half a cup of dry oatmeal',
    },
    {
        name: 'PB&J',
        protein: 7,
        carbs: 43,
        fat: 15,
        info: '2 tbsp of peanut butter, 1 tbsp jelly (strawberry squeeze non sugar free)',
    },
    {
        name: 'Quick Beef and Rice',
        protein: 43,
        carbs: 75,
        fat: 11,
        info: 'Pack of whole grain medley and 2 servings of beef fajitas',
    },
    {
        name: 'Isopure Protein',
        protein: 25,
        carbs: 0,
        fat: 0,
    },
    {
        name: 'Turkey/Rice Lunch',
        protein: 29,
        carbs: 64,
        fat: 10,
        info: '1lb of turkey, half a cup of cooked rice, 1 tbsp sauce, cup of veggies',
    },
    {
        name: 'Half of a liquid IV',
        protein: 0,
        carbs: 12,
        fat: 0,
    },
    {
        name: 'Salmon Meal from Cheddars',
        protein: 52,
        carbs: 74,
        fat: 43,
        info: '8oz salmon, baked potato, caesar salad',
    },
    {
        name: 'Chipotle Burrito',
        protein: 93,
        carbs: 126,
        fat: 60.5,
    },
]

export const user = {
    name: 'Jimmy',
    currentProtein: 0,
    currentCarbs: 0,
    currentFat: 0,
    targetProtein: 265,
    targetCarbs: 330,
    targetFat: 80,
}

export const push = [
    {
        id: 0,
        name: 'Inclined Barbell Bench',
        startingWeight: 135,
        finishingWeight: 155,
        sets: 3,
        targetReps: 8,
    },
    {
        id: 1,
        name: 'Dumbbell Overhead Press',
        startingWeight: 20,
        finishingWeight: 25,
        sets: 3,
        targetReps: 15,
    },
    {
        id: 2,
        name: 'Flat Dumbbell Press',
        startingWeight: 65,
        finishingWeight: 65,
        sets: 3,
        targetReps: 10,
    },
    {
        id: 3,
        name: 'Lat Raises',
        startingWeight: 15,
        finishingWeight: 15,
        sets: 3,
        targetReps: 10,
    },
    {
        id: 4,
        name: 'Cable Chest Fly',
        startingWeight: 130,
        finishingWeight: 145,
        sets: 3,
        targetReps: 10,
    },
    {
        id: 5,
        name: 'Tricep Push Downs',
        startingWeight: 72.5,
        finishingWeight: 72.5,
        sets: 3,
        targetReps: 15,
    },
]

export const pull = [
    {
        id: 0,
        name: 'Barbell Row',
        startingWeight: 115,
        finishingWeight: 135,
        sets: 3,
        targetReps: 10,
    },
    {
        id: 1,
        name: 'Overhand Pull Downs',
        startingWeight: 145,
        finishingWeight: 145,
        sets: 3,
        targetReps: 10,
    },
    {
        id: 2,
        name: 'Curls',
        startingWeight: 50,
        finishingWeight: 50,
        sets: 3,
        targetReps: 10,
    },
    {
        id: 3,
        name: 'Underhand Pull Downs',
        startingWeight: 180,
        finishingWeight: 180,
        sets: 3,
        targetReps: 10,
    },
    {
        id: 4,
        name: 'Face Pulls',
        startingWeight: 35,
        finishingWeight: 42.5,
        sets: 3,
        targetReps: 15,
    },
    {
        id: 5,
        name: 'Machine Row',
        startingWeight: 100,
        finishingWeight: 115,
        sets: 3,
        targetReps: 15,
    },
]

export const legs = [
    {
        id: 0,
        name: 'Barbell Front Squat',
        startingWeight: 115,
        finishingWeight: 135,
        sets: 3,
        targetReps: 6,
    },
    {
        id: 1,
        name: 'Hip Thrusts',
        startingWeight: 90,
        finishingWeight: 90,
        sets: 3,
        targetReps: 15,
    },
    {
        id: 2,
        name: 'Split Squats',
        startingWeight: 20,
        finishingWeight: 20,
        sets: 3,
        targetReps: 8,
    },
    {
        id: 3,
        name: 'Stiff Leg Deadlift',
        startingWeight: 100,
        finishingWeight: 100,
        sets: 3,
        targetReps: 10,
    },
    {
        id: 4,
        name: 'Calf Raise',
        startingWeight: 90,
        finishingWeight: 90,
        sets: 3,
        targetReps: 15,
    },
]
